arch:
  - aarch64
  - amd64

name: Sonorium
description: Ambient soundscape mixer with crossfade looping for Home Assistant
slug: sonorium
version: 1.3.1
url: https://github.com/synssins/sonorium

init: false
homeassistant_api: true
audio: false

map:
  - media:rw
  - config:rw

ports:
  8080/tcp: 8007

panel_icon: mdi:waveform

options:
  sonorium__stream_url: "http://homeassistant.local:8007"
  sonorium__path_audio: "/media/sonorium"

schema:
  sonorium__stream_url: str
  sonorium__path_audio: str

webui: http://[HOST]:[PORT:8080]/
